version: '2'

services:
  haproxy:
    image: haproxy:1.8
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - log
      - web
      - fpm

  syslog:
    image: balabit/syslog-ng
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    networks:
      - log

  web1:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-www.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  web2:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-www.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  php1:
    image: php:7-fpm
    volumes:
      - ./html:/var/www/html
      - ./php-ping.conf:/usr/local/etc/php-fpm.d/ping.conf
    networks:
      - fpm

  php2:
    image: php:7-fpm
    volumes:
      - ./html:/var/www/html
      - ./php-ping.conf:/usr/local/etc/php-fpm.d/ping.conf
    networks:
      - fpm

networks:
  fpm:
  web:
  log:

